### ISSUE TITLE
(Overflow) Scrolling completely does not show all components

### ISSUE THREAD

**Issue by Exiledz5155** [Exiledz5155/mp3-metadata#27]
This is an issue in SongDisplay and FileHub,

Filehub:

When FileHubAlbumCards are expanded (accordion) it seems that the nested songs don't count towards the overflow.

This results in not being able to fully see the content of the filehub even after scrolling down.

To replicate - open 2-3 albums (that aren't the last album) and scroll down. You'll see that you cannot scroll down far enough to view the final album.

SongDisplay:

Has a similar issue, to replicate just scroll down, you'll see the last song get cut off- it doesn't display fully.

**Comment by ducttri** [comment]
Need to add a flex display attribute to any components that have children dynamically changing with size.
